<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Cache\RefinableCacheableDependencyInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\views_ui\ViewUI;

/**
 * Implements hook_form_alter().
 */
function admin_dialogs_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  \Drupal::service('admin_dialogs.module')->form_alter($form, $form_state, $form_id);
}

/**
 * Implements hook_entity_operation_alter().
 */
function admin_dialogs_entity_operation_alter(array &$operations, EntityInterface $entity) {
  \Drupal::service('admin_dialogs.module')->entity_operation_alter($operations, $entity);
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function admin_dialogs_menu_local_tasks_alter(&$data, $route_name, RefinableCacheableDependencyInterface &$cacheability) {
  \Drupal::service('admin_dialogs.module')->menu_local_tasks_alter($data, $route_name, $cacheability);
}

/**
 * Implements hook_menu_local_actions_alter().
 */
function admin_dialogs_menu_local_actions_alter(&$local_actions) {
  \Drupal::service('admin_dialogs.module')->menu_local_actions_alter($local_actions);
}

/**
 * Implements hook_entity_type_build().
 */
function admin_dialogs_entity_type_build(array &$entity_types) {
  \Drupal::service('admin_dialogs.module')->entity_type_build($entity_types);
}

/**
 * Implements hook_page_attachments().
 */
function admin_dialogs_page_attachments(array &$attachments) {
  \Drupal::service('admin_dialogs.module')->page_attachments($attachments);
}

/**
 * Implements hook_views_ui_display_top_links_alter().
 */
function admin_dialogs_views_ui_display_top_links_alter(&$links, ViewUI $view, $display_id) {
  \Drupal::service('admin_dialogs.module')->views_ui_display_top_links($links, $view, $display_id);
}

/**
 * Implements hook_theme().
 */
function admin_dialogs_theme() {
  return \Drupal::service('admin_dialogs.module')->theme();
}

/**
 * Implements hook_help().
 */
function admin_dialogs_help($route_name, RouteMatchInterface $route_match) {
  return \Drupal::service('admin_dialogs.module')->help($route_name, $route_match);
}
