################
# Based on DrupalCI GitLabCI template
#
# With thanks to:
#   * The GitLab Acceleration Initiative participants
#   * DrupalSpoons
################

include:
  ################
  # DrupalCI includes:
  # As long as you include this, any future includes added by the Drupal Association will be accessible to your pipelines automatically.
  # View these include files at https://git.drupalcode.org/project/gitlab_templates/
  ################
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - '/includes/include.drupalci.main.yml'
      - '/includes/include.drupalci.variables.yml'
      - '/includes/include.drupalci.workflows.yml'

################
# Pipeline configuration variables
#
# Docs at https://git.drupalcode.org/project/gitlab_templates/-/blob/main/includes/include.drupalci.variables.yml
################
variables:
  # Generate a new phpstan baseline.
  GENERATE_PHPSTAN_BASELINE:
    value: "0"

################
# Install module in different environments using composer
################
composer:
  parallel:
    matrix:
      # Drupal 10 (min PHP).
      - _TARGET_PHP: [$CORE_PHP_MIN]
        _TARGET_CORE:
          - $CORE_PREVIOUS_STABLE
          - $CORE_STABLE
          - $CORE_NEXT_MINOR
      # Drupal 10 (max PHP) & 11.
      - _TARGET_PHP: [$CORE_PHP_MAX]
        _TARGET_CORE:
          - $CORE_PREVIOUS_STABLE
          - $CORE_STABLE
          - $CORE_MAJOR_DEVELOPMENT

################
# Run tests in different environments
################
phpunit:
  needs:
    - job: composer
      parallel:
        matrix:
          - _TARGET_PHP: $CORE_PHP_MIN
            _TARGET_CORE: $CORE_PREVIOUS_STABLE
          - _TARGET_PHP: $CORE_PHP_MAX
            _TARGET_CORE: $CORE_PREVIOUS_STABLE
          - _TARGET_PHP: $CORE_PHP_MIN
            _TARGET_CORE: $CORE_STABLE
          - _TARGET_PHP: $CORE_PHP_MAX
            _TARGET_CORE: $CORE_STABLE
          - _TARGET_PHP: $CORE_PHP_MAX
            _TARGET_CORE: $CORE_MAJOR_DEVELOPMENT

phpunit (max PHP version):
  extends: phpunit
  needs:
    - job: composer
      parallel:
        matrix:
          - _TARGET_PHP: $CORE_PHP_MAX
            _TARGET_CORE: $CORE_STABLE
  variables:
    _TARGET_PHP: $CORE_PHP_MAX

# Future versions, hence breaks may arrive at any time: failure is allowed.
phpunit (next minor):
  allow_failure: true
  extends: phpunit
  needs:
    - job: composer
      parallel:
        matrix:
          - _TARGET_PHP: $CORE_PHP_MIN
            _TARGET_CORE: $CORE_NEXT_MINOR
phpunit (next major):
  allow_failure: true
  extends: phpunit
  needs:
    - job: composer
      parallel:
        matrix:
          - _TARGET_PHP: $CORE_PHP_MAX
            _TARGET_CORE: $CORE_MAJOR_DEVELOPMENT
  before_script:
    # If the module already supports Drupal 11, do nothing, otherwise, claim Drupal 11 support for testing purposes.
    - grep -q "\^11" *.info.yml || (grep -q "\^10" *.info.yml && sed -i "s/\^10/\^10 \|\| ^11/" *.info.yml)
  variables:
    _TARGET_PHP: $CORE_PHP_MAX
